### ISSUE TITLE
Add timeout option

### ISSUE THREAD

**Issue by baterflyrity** [thombashi/subprocrunner#1]
Can someone please add explicit [timeout](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) option.

It can be easily implemented with

    SubprocessRunner("ping ya.ru -t").run(timeout=2)

but IDE support for explicit option name is more beautiful and error-safe.

**Comment by thombashi** [comment]
@baterflyrity 
Thank you for your feedback.

I had added timeout keyword argument to `run` method at `subprocrunner 1.3.0`
